[general]
import = [
    #   "~/.config/alacritty/catppuccin-latte.toml"
    #   "~/.config/alacritty/catppuccin-frappe.toml"
    #   "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml",
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 4
y = 4
